### ISSUE TITLE
support file manage for /etc/libvirt/libvirtd.conf

### ISSUE THREAD

**Issue by mcaj** [openSUSE/salt-formulas#24]
In the /libvirt-formula/libvirt/files/etc/libvirt you have only files 
* [libvirt.conf] (https://github.com/openSUSE/salt-formulas/blob/main/libvirt-formula/libvirt/files/etc/libvirt/libvirt.conf)
* [qemu.conf](https://github.com/openSUSE/salt-formulas/blob/main/libvirt-formula/libvirt/files/etc/libvirt/qemu.conf)

our cluster need to have there the file libvirtd.conf to enable life migration.
I would be nice it this file will be a jinja template and data into it loaded from pillars
need it options are:
* listen_tls  = 0 (default)
* listen_tcp = 1 (default)
* tls_port = "16514" (default)
* tcp_port = "16509" (default)
* listen_addr = "192.168.0.1" (default)
* mdns_name = "NAME or fqdn of the node"
* auth_tcp = "none" (default)
* max_clients = 128 (default)

in the file it more options but this once are let say a most need it one

https://github.com/openSUSE/salt-formulas/blob/6b1db92cfef817e9a15336184e2b52b2a48d55e0/libvirt-formula/libvirt/init.sls#L37

**Comment by tacerus** [comment]
Hi,

I think this will be resolved with https://github.com/openSUSE/salt-formulas/pull/28. It allows `libvirt.conf`, `libvirtd.conf` and `qemu.conf` to be configured using the `libvirt`, `libvirtd` and `qemu` pillars - all options can be fed using the pillar, it does not limit which ones can be used.

I added a `max_client` default, as I think it makes sense compared to the 5000 client default shipped with libvirt. The other settings I suggest setting using the pillar if needed, as the shipped defaults are reasonable. Most options should not be necessary anymore anyways (for example `listen_tls`/`listen_tcp` are sort of deprecated in favor of systemd sockets).

Let me know should you deem any other settings reasonable to be set in the formula defaults or whether the new pillar feature is good enough.

**Comment by tacerus** [comment]
This has been implemented with #28, as discussed.
