### ISSUE TITLE
infrastructure: allow variable network environment

### ISSUE THREAD

**Issue by tacerus** [openSUSE/salt-formulas#52]
As discussed in https://github.com/openSUSE/salt-formulas/pull/49, the Saltenv used for network pillars is currently hardcoded. Moving it to a pillar variable would make sense, though it should be one variable which updates the needful in all places throughout the pillar. This should be investigated in the pillar setup and then facilitated in the formula.

**Comment by cboltz** [comment]
Fixed in #56
