### ISSUE TITLE
Section order in spec randomly changes

### ISSUE THREAD

**Issue by cboltz** [openSUSE/salt-formulas#74]
https://github.com/openSUSE/salt-formulas/pull/73 moved the sections for multipath-formula around for no obvious reason. My guess is that `directories = Path('.').glob('*{}/'.format(pattern))` in `genspec.py` gives its results in filesystem order (aka semi-random).

I'd  recommend to add a `sorted(...)` around setting ´directories´.

**Comment by tacerus** [comment]
I was mildly annoyed by the reordering as well, but didn't investigate further. ;-)

Thanks for the suggestion, we can try that.

**Comment by cboltz** [comment]
Fixed with #78
